// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4uaMOudUSdF7UepcNPPIiMGwU7CHDzW8',
    appId: '1:948660570704:web:a2ff79a66cb4e440ad1f55',
    messagingSenderId: '948660570704',
    projectId: 'projeto-flutter-62176',
    authDomain: 'projeto-flutter-62176.firebaseapp.com',
    storageBucket: 'projeto-flutter-62176.firebasestorage.app',
    measurementId: 'G-D8ESEZCYRN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnzJq77a0m1tN7k3q0MS5wG0Ns6rdvgJc',
    appId: '1:948660570704:ios:8c95f490e2277459ad1f55',
    messagingSenderId: '948660570704',
    projectId: 'projeto-flutter-62176',
    storageBucket: 'projeto-flutter-62176.firebasestorage.app',
    iosBundleId: 'com.fernanda.pokemonapp',
  );
}
